"""Collect the headline results and attack training logs into frontend/data.js for the dashboard.

Reads only committed files (results/headline*.json, results/logs/*.csv); no torch needed.
Run from anywhere:  python frontend/build_data.py
"""
import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = Path(__file__).resolve().parent / "data.js"

# headline file -> (scenario id, display label, short description)
SCENARIOS = [
    ("headline_liqbase_uwcash.json", "liqbase_uwcash", "Liquidity risk + unwind cost",
     "No proportional cost; stochastic liquidity (spread + square-root impact), hedge unwound in cash at exercise."),
    ("headline_c0.005_uwcash.json", "c0.005_uwcash", "0.5% cost + unwind cost",
     "Proportional transaction cost c = 0.5%, plus the cost of unwinding the hedge at exercise."),
    ("headline_c0.005.json", "c0.005", "0.5% transaction cost",
     "Proportional transaction cost c = 0.5% on every rebalance; unwind at exercise not charged."),
    ("headline.json", "frictionless", "Frictionless",
     "No transaction costs and no liquidity effects."),
]

LOG_PREFIX = {"gda": "exploit", "fixed-lsm": "exploit-fixed-lsm", "fixed-maturity": "exploit-fixed-maturity"}
TRAIN_PREFIX = {"gda": "gda", "fixed-lsm": "fixed-lsm", "fixed-maturity": "fixed-maturity"}


def clean(x):
    """JSON-safe float (NaN/inf -> None)."""
    if isinstance(x, float) and not math.isfinite(x):
        return None
    return x


def read_log(path: Path, step_key: str, value_key: str):
    if not path.exists():
        return None
    out = []
    with path.open() as f:
        for row in csv.DictReader(f):
            v = float(row[value_key])
            out.append([int(row[step_key]), clean(v)])
    return out


def run_stem(source: str, suffix: str) -> str:
    return f"lam1_a0p9_s1234_heuristic{suffix}_reduced"


def scenario(fname, sid, label, desc):
    d = json.loads((RESULTS / fname).read_text())
    suffix = d.get("suffix") or ""
    hedgers = []
    for h in d["hedgers"]:
        src = h["source"]
        stem = run_stem(src, suffix)
        attacks = [dict(name=k, cvar=v["cvar"], se=v["se"], mean_ex_time=v["mean_ex_time"],
                        frac_early=v["frac_early"]) for k, v in h["evals"].items()]
        hedgers.append(dict(
            source=src, label=h["label"], trained_against=h["trained_against"],
            trained_cvar=h["trained_cvar"], trained_se=h["trained_se"],
            worst_attack=h["worst_attack"], worst_cvar=h["worst_cvar"], worst_se=h["worst_se"],
            rise=h["rise"], rise_se=h["rise_se"], rel_rise=h["rel_rise"],
            train_minutes=h.get("train_minutes"),
            vs_adv_under_fresh=h.get("vs_adv_under_fresh"),
            vs_adv_under_fresh_se=h.get("vs_adv_under_fresh_se"),
            attacks=attacks,
            # fresh adversary's CVaR on its training batch, by step (hard rule)
            attack_curve=read_log(RESULTS / "logs" / f"{LOG_PREFIX[src]}_{stem}.csv", "step", "hard_cvar"),
            # hedger training: GDA logs hard CVaR vs its co-trained adversary, fixed-rule hedgers their loss
            train_curve=read_log(RESULTS / "logs" / f"{TRAIN_PREFIX[src]}_{stem}.csv", "it",
                                 "hard_cvar" if src == "gda" else "loss"),
        ))
    return dict(
        id=sid, label=label, description=desc,
        lam=d["lam"], alpha=d["alpha"], c=d.get("c", 0.0), unwind=d.get("unwind") or "none",
        liquidity=(d.get("liquidity") or {}).get("name") if (d.get("liquidity") or {}).get("enabled") else None,
        batch_log2=d["batch_log2"], outer_iters=d["outer_iters"],
        no_hedge=d["no_hedge"], hedgers=hedgers,
        hedge_by_liquidity=d.get("hedge_by_liquidity"),
    )


def main():
    data = dict(scenarios=[scenario(*s) for s in SCENARIOS if (RESULTS / s[0]).exists()])
    js = "// Generated by frontend/build_data.py from results/ - do not edit by hand.\n"
    js += "window.DASHBOARD_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n"
    OUT.write_text(js)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(js) / 1024:.1f} KB, {len(data['scenarios'])} scenarios)")


if __name__ == "__main__":
    main()
